version: '3.8'
networks:
  global:

services:
  db:
    image: postgres:15
    restart: always
    shm_size: '10g'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-grafana-user.sql:/docker-entrypoint-initdb.d/init-grafana-user.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - global
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:pass@db/scada_repo
      PHX_HOST: localhost
      PORT: "4000"
    networks:
      - global
    ports:
      - "4000:4000"
